package examples.parsing.csv;

import za.ac.sun.cs.coastal.Symbolic;

/**
 * A parser that accepts the inputs generated by the regex a (, a)*
 * @author phillip
 *
 */
public class SimpleCSV {
	
	public static void main(String[] args) {
		parseCSV("a,a,a".toCharArray());
	}

	public static boolean parseCSV(char[] text) {
	    int i = 0;

	    if (text[i] == 'a') {
	        i++;
	    } else {
	    	Symbolic.mark(0);
	    	return false;
	    }

	    while (i < text.length) {
	        if (text[i] == ',') {
	            i++;
	        } else {
	        	Symbolic.mark(0);
	            return false;
	        }

	        if (i == text.length) {
	        	Symbolic.mark(0);
	            return false;
	        }

	        if (text[i] == 'a') {
	            i++;
	        } else {
	        	Symbolic.mark(0);
	            return false;
	        }
	    }

	    Symbolic.mark(1);
	    return true;
	}		
}


